import * as PLACEHOLDERS from './placeholders';

export const SNIPE_BODY_TEMPLATE = (
`[size=5]會員編號：${PLACEHOLDERS.USER_ID}
會員名稱：${PLACEHOLDERS.USERNAME}
註冊日期：${PLACEHOLDERS.REGISTRATION_DATE}[/size=5]

${PLACEHOLDERS.SNIPE_LABELS_CONTENT}`
);

export const SNIPE_LABEL_ITEM_CONTENT_TEMPLATE = (
`[size=5]【${PLACEHOLDERS.LABEL_TEXT}】
事蹟：${PLACEHOLDERS.REASON}[/size=5]
詳細來源：${PLACEHOLDERS.SOURCE_URL}`
);
